# NumPy -- array and vector calculate

## 1.Introduction

In [2]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [5]:
data = np.array([[0.9526,-0.246,-0.8856],[0.5639,0.2379,0.9104]])
data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [9]:
# vector calculate just like scalar 
data * 10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [11]:
data + data

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

In [20]:
# ndarray is a Homogeneous data multidimensional container （同构数据多维容器）
# all elements have some type
data.dtype

dtype('float64')

In [16]:
# set up 
# np.array accept all of the sequence-like object
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [17]:
# input nested list will be transform into a muti-dimension array
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
# show dimension
arr2.ndim

2

In [19]:
# show shape
arr2.shape

(2, 4)

In [21]:
# if you don't assign a concretely type when initialize, numpy would automatically deduce a properly type for it
arr1.dtype

dtype('float64')

In [43]:
arr2.dtype

dtype('int32')

In [42]:
# except just use np.array,there are some interesting funtion that you can use to creat a array
np.zeros(3)

array([ 0.,  0.,  0.])

In [29]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [30]:
np.ones((3,3,3))

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [33]:
# np.empty would return some uninitialized garbage value, rather than all zero array.
np.empty(9)

array([  7.91866190e-312,   7.91866190e-312,   7.91865971e-312,
         7.91866190e-312,   7.91866190e-312,   7.91866190e-312,
         7.91866190e-312,   7.91866190e-312,   7.91866190e-312])

In [34]:
# range function in numpy
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
# x-like function will create a all ones/zeros/empty array as the array that you input
np.ones_like(arr1)

array([ 1.,  1.,  1.,  1.,  1.])

In [36]:
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
np.empty_like(arr2)

array([[         0, 1075314688,          0, 1075707904],
       [         0, 1075838976,          0, 1072693248]])

In [39]:
# identity matrix
# like eye() in matlab
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [40]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## 2.ndarray's dtype

In [46]:
arr3 = np.array([1,2,3],dtype=np.int32)
arr3.dtype

dtype('int32')

In [48]:
# you can transform the type of a array by np.astype
arr4 = arr3.astype(float64)
arr4.dtype

dtype('float64')

In [55]:
# or just input a array's type,numpy would get its dtype as your parameter
arr5 = arr3.astype(arr4.dtype)
arr5.dtype

dtype('float64')

In [52]:
# if all of the elements is number in a string array , you can also transform it to a num array.
arr_str = np.array(['1','2','3'])
arr_strToNum = arr_str.astype(int32)
arr_strToNum

array([1, 2, 3])

## 3.calculate between vector and scalar

In [56]:
# vector & vector
arr6 = np.array([[1,2,3],[4,5,6]])
arr6 * arr6

array([[ 1,  4,  9],
       [16, 25, 36]])

In [57]:
arr6 + arr6

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [58]:
arr6 / arr6

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [59]:
# vector & scalar
arr6 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [60]:
1/arr6

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [61]:
arr6 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

## 4.fundmental index and slice

In [72]:
# different from python's slice,the numpy'slice is a view of origin array which means all the modify on slice would be directly effect 
# in its origin array 
# so if you only want get a copy instead of a view of origin array, you can
arr6[1].copy()

array([10, 10,  6])

In [68]:
# axis0 -- row ; axis1 -- column
arr6[1][0:2]

array([4, 5])

In [74]:
# some to the above syntax
arr6[1, 0:2]

array([10, 10])

In [70]:
arr6[1][0:2] = 10
arr6

array([[ 1,  2,  3],
       [10, 10,  6]])

In [77]:
# only ： would select all of the axis
arr6[0 , :]

array([1, 2, 3])

## 5.bool index